const Map<String, String> appStringsEn = {
  'appName': 'Daily Vault',
  'appTagline': 'Secure storage for passwords, notes & documents',
  'splashLoading': 'Unlocking your vault...',
  'onboardingTitle1': 'Your private vault',
  'onboardingDesc1': 'Store passwords, secret notes and personal documents in one secure place. Everything stays on your device.',
  'onboardingTitle2': 'Lock with PIN or fingerprint',
  'onboardingDesc2': 'Protect your vault with a PIN code or biometric unlock. Your data is always encrypted and private.',
  'onboardingTitle3': 'Earn stars & customize',
  'onboardingDesc3': 'Earn free stars by using the app daily, or buy star packs via Google Play. Unlock themes, backgrounds, skins and premium features.',
  'getStarted': 'Get started',
  'skip': 'Skip',
  'next': 'Next',
  'navHome': 'Home',
  'navBrowse': 'Browse',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'homeTitle': 'Daily Vault',
  'homeSubtitle': 'Your secure personal storage',
  'homeEmpty': 'Your vault is empty. Add your first item!',
  'quickAdd': 'Quick add',
  'recentItems': 'Recent',
  'categoryPasswords': 'Passwords',
  'categoryNotes': 'Secret notes',
  'categoryDocuments': 'Documents',
  'categoryPasswordsDesc': 'Login credentials & accounts',
  'categoryNotesDesc': 'Private notes & secrets',
  'categoryDocumentsDesc': 'Personal files & attachments',
  'itemsCount': '{count} items',
  'passwordsTitle': 'Passwords',
  'passwordsSubtitle': 'Saved login credentials',
  'notesTitle': 'Secret notes',
  'notesSubtitle': 'Private notes & secrets',
  'documentsTitle': 'Documents',
  'documentsSubtitle': 'Personal files & attachments',
  'browseTitle': 'Browse',
  'browseSubtitle': 'All vault items',
  'filterAll': 'All',
  'filterPasswords': 'Passwords',
  'filterNotes': 'Notes',
  'filterDocuments': 'Docs',
  'filterFavorites': 'Favorites',
  'browseEmpty': 'No items yet. Start adding from Home!',
  'searchHint': 'Search vault...',
  'addItem': 'Add item',
  'editItem': 'Edit item',
  'fieldTitle': 'Title',
  'fieldUsername': 'Username',
  'fieldPassword': 'Password',
  'fieldUrl': 'Website URL',
  'fieldContent': 'Content',
  'fieldFile': 'File',
  'fieldNotes': 'Notes (optional)',
  'fieldNotesHint': 'Any additional notes...',
  'pickFile': 'Pick file',
  'changeFile': 'Change file',
  'copyPassword': 'Copy password',
  'copyUsername': 'Copy username',
  'passwordCopied': 'Password copied!',
  'usernameCopied': 'Username copied!',
  'showPassword': 'Show',
  'hidePassword': 'Hide',
  'favorite': 'Favorite',
  'unfavorite': 'Unfavorite',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'deleteConfirm': 'Delete this item permanently?',
  'itemSaved': 'Item saved!',
  'itemDeleted': 'Item deleted',
  'listEmpty': 'Nothing here yet',
  'listEmptyAction': 'Add first item',
  'limitReached': 'Free limit reached ({limit} items) — unlock unlimited in Shop',
  'setupPinTitle': 'Create PIN',
  'setupPinDesc': 'Set a 4-digit PIN to protect your vault',
  'confirmPinTitle': 'Confirm PIN',
  'confirmPinDesc': 'Enter your PIN again to confirm',
  'pinMismatch': 'PINs do not match. Try again.',
  'pinTooShort': 'PIN must be at least 4 digits',
  'lockTitle': 'Daily Vault',
  'lockSubtitle': 'Enter PIN to unlock',
  'lockWrongPin': 'Wrong PIN. Try again.',
  'unlockWithBiometric': 'Unlock with fingerprint',
  'forgotPin': 'Forgot PIN?',
  'forgotPinTitle': 'Reset vault',
  'forgotPinDesc': 'Daily Vault stores everything locally. There is no way to recover a forgotten PIN without your data.',
  'forgotPinOptionBio': 'If fingerprint unlock is enabled, use it to open the app, then go to Settings → Change PIN.',
  'forgotPinOptionReset': 'If you cannot unlock, you must reset the vault. This permanently deletes all passwords, notes and documents on this device.',
  'forgotPinConfirm': 'Reset & create new PIN',
  'forgotPinCancel': 'Cancel',
  'forgotPinDone': 'Vault reset. Set a new PIN.',
  'biometricReason': 'Authenticate to unlock Daily Vault',
  'changePin': 'Change PIN',
  'changePinDesc': 'Update your vault PIN',
  'oldPin': 'Current PIN',
  'newPin': 'New PIN',
  'confirmNewPin': 'Confirm new PIN',
  'pinChanged': 'PIN changed successfully',
  'pinChangeFailed': 'Could not change PIN',
  'pinSameAsOld': 'New PIN must be different from current PIN',
  'changePinStepCurrent': 'Enter your current 4-digit PIN',
  'changePinStepNew': 'Choose a new 4-digit PIN',
  'changePinStepConfirm': 'Enter the new PIN again to confirm',
  'biometricLock': 'Fingerprint unlock',
  'biometricLockDesc': 'Use fingerprint or face to unlock',
  'biometricNotAvailable': 'Biometric not available on this device',
  'securitySection': 'Security',
  'adPlaceholder': 'Ad — Remove ads in Shop',
  'settingsTitle': 'Settings',
  'settingsSubtitle': 'Security & preferences',
  'activeCustomization': 'Active look',
  'activeTheme': 'Theme',
  'activeBackground': 'Background',
  'activeSkin': 'Card style',
  'appearance': 'Appearance',
  'darkMode': 'Dark mode',
  'premiumFeatures': 'Premium',
  'exportData': 'Export vault',
  'exportDataDesc': 'Share all vault data as text',
  'exportEmpty': 'Nothing to export',
  'exportDone': 'Export shared!',
  'exportDate': 'Export date',
  'exportLocked': 'Unlock export in Shop',
  'other': 'Other',
  'language': 'Language',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'openShop': 'Open Shop',
  'openShopDesc': 'Buy stars, themes & features',
  'privacyPolicy': 'Privacy policy',
  'copyright': '© Daily Vault. All data stored locally on your device.',
  'themeDefault': 'Default',
  'bgDefault': 'Default',
  'skinDefault': 'Default',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Stars, themes & premium features',
  'shopBalance': 'Your stars',
  'shopBuyStars': 'Buy stars',
  'shopBuyStarsDesc': 'Get more stars via Google Play',
  'shopEarnStars': 'Earn stars',
  'shopDailyReward': 'Daily reward',
  'shopDailyRewardDesc': 'Claim {amount} stars once per day',
  'shopClaim': 'Claim',
  'shopClaimed': 'Claimed today',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Card styles',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'shopOwned': 'Owned',
  'shopActive': 'Active',
  'shopApply': 'Apply',
  'shopResetDefault': 'Reset to default',
  'shopBuy': 'Buy',
  'shopPrice': '{price} stars',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Enjoy an ad-free experience forever',
  'shopThemeOcean': 'Ocean Blue',
  'shopThemeOceanDesc': 'Cool blue tones for focus',
  'shopThemeMidnight': 'Midnight Sky',
  'shopThemeMidnightDesc': 'Deep sky blue theme',
  'shopThemeEmerald': 'Emerald Guard',
  'shopThemeEmeraldDesc': 'Fresh green security theme',
  'shopThemeRoyal': 'Royal Purple',
  'shopThemeRoyalDesc': 'Elegant purple premium look',
  'shopBgVault': 'Vault Shield',
  'shopBgVaultDesc': 'Deep navy vault gradient',
  'shopBgOcean': 'Ocean Wave',
  'shopBgOceanDesc': 'Calm ocean gradient background',
  'shopBgAurora': 'Aurora',
  'shopBgAuroraDesc': 'Northern lights gradient',
  'shopBgGalaxy': 'Galaxy',
  'shopBgGalaxyDesc': 'Deep space gradient',
  'shopSkinNeon': 'Neon Edge',
  'shopSkinNeonDesc': 'Glowing teal card borders',
  'shopSkinClassic': 'Classic Gold',
  'shopSkinClassicDesc': 'Warm gold-bordered cards',
  'shopSkinGlass': 'Glass Frost',
  'shopSkinGlassDesc': 'Frosted glass card effect',
  'shopFeatUnlimitedItems': 'Unlimited items',
  'shopFeatUnlimitedItemsDesc': 'No limit on passwords, notes & documents',
  'shopFeatExport': 'Export data',
  'shopFeatExportDesc': 'Export your entire vault',
  'shopFeatCustomFolders': 'Custom folders',
  'shopFeatCustomFoldersDesc': 'Organize items in custom folders',
  'shopFeatSecureSharing': 'Secure sharing',
  'shopFeatSecureSharingDesc': 'Share items with extra protection',
  'shopFeatNoWatermark': 'No watermark',
  'shopFeatNoWatermarkDesc': 'Clean exports without branding',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed. Try again.',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'coinsAdded': 'Stars added to your balance!',
  'removeAdsUnlocked': 'Ads removed!',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'addPasswordRewardEarned': 'Stars earned for saving a password!',
  'addNoteRewardEarned': 'Stars earned for saving a note!',
  'addDocumentRewardEarned': 'Stars earned for saving a document!',
  'shareRewardEarned': 'Stars earned for sharing!',
  'billingDisabled': 'Google Play billing is temporarily unavailable',
  'configNetworkError': 'Could not reach server — using cached settings',
  'configTimeout': 'Server timeout — using cached settings',
  'coinPackTitle': 'Buy stars',
  'coinPackSubtitle': 'Choose a star pack',
  'restorePurchases': 'Restore purchases',
  'privacyTitle': 'Privacy Policy',
  'privacyIntro': 'Daily Vault stores all your data locally on your device. We do not collect, transmit or sell your personal information.',
  'privacyData': 'Your passwords, notes and documents never leave your device unless you explicitly export or share them.',
  'privacyContact': 'Contact: support@dailyvault.app',
  'logNotes': 'Notes',
  'yourWallet': 'Your wallet',
  'coinsLabel': 'Stars',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': 'Get star packs via Google Play',
  'yourCoins': 'You have {count} stars',
  'shopClaimedDaily': 'Claimed today',
  'shopClaimDaily': 'Claim',
  'earnStepSavePassword': 'Save password',
  'earnStepSavePasswordDesc': '+3 stars per password (max 10/day)',
  'earnStepSaveNote': 'Save note',
  'earnStepSaveNoteDesc': '+2 stars per note (max 15/day)',
  'earnStepSaveDocument': 'Save document',
  'earnStepSaveDocumentDesc': '+5 stars per document (max 3/day)',
  'earnStepShare': 'Share vault',
  'earnStepShareDesc': '+5 stars when sharing export',
  'buyWithGooglePlay': 'Buy with Google Play',
  'shopBrowse': 'Browse shop',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Reset default',
  'resetToDefault': 'Reset to default',
  'owned': 'Owned',
  'openingBilling': 'Opening Google Play...',
  'removeAdsIap': 'Remove ads via Google Play',
  'processingPurchase': 'Processing purchase...',
  'billingUnavailable': 'Billing unavailable on this device',
  'productsNotFound': 'Products not found in store',
  'earnCoinsHint': 'Earn stars by saving items or claim daily reward',
  'coinPack': 'Star pack {num}',
  'coinAmount': '{count} stars',
  'coinRewardSub': 'Balance: {balance} stars',
};
