const Map<String, String> appStringsVi = {
  'appName': 'Daily Vault',
  'appTagline': 'Kho lưu trữ an toàn cho mật khẩu, ghi chú & tài liệu',
  'splashLoading': 'Đang mở kho bảo mật...',
  'onboardingTitle1': 'Kho cá nhân của bạn',
  'onboardingDesc1': 'Lưu mật khẩu, ghi chú bí mật và tài liệu cá nhân ở một nơi an toàn. Mọi thứ lưu trên thiết bị của bạn.',
  'onboardingTitle2': 'Khóa bằng PIN hoặc vân tay',
  'onboardingDesc2': 'Bảo vệ kho bằng mã PIN hoặc mở khóa sinh trắc học. Dữ liệu luôn được mã hóa và riêng tư.',
  'onboardingTitle3': 'Kiếm sao & tùy chỉnh',
  'onboardingDesc3': 'Kiếm sao miễn phí khi dùng app hàng ngày, hoặc mua gói sao qua Google Play. Mở khóa theme, hình nền, skin và tính năng cao cấp.',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',
  'navHome': 'Trang chủ',
  'navBrowse': 'Duyệt',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'homeTitle': 'Daily Vault',
  'homeSubtitle': 'Kho lưu trữ cá nhân an toàn',
  'homeEmpty': 'Kho trống. Thêm mục đầu tiên!',
  'quickAdd': 'Thêm nhanh',
  'recentItems': 'Gần đây',
  'categoryPasswords': 'Mật khẩu',
  'categoryNotes': 'Ghi chú bí mật',
  'categoryDocuments': 'Tài liệu',
  'categoryPasswordsDesc': 'Tài khoản & thông tin đăng nhập',
  'categoryNotesDesc': 'Ghi chú riêng tư & bí mật',
  'categoryDocumentsDesc': 'File cá nhân & đính kèm',
  'itemsCount': '{count} mục',
  'passwordsTitle': 'Mật khẩu',
  'passwordsSubtitle': 'Thông tin đăng nhập đã lưu',
  'notesTitle': 'Ghi chú bí mật',
  'notesSubtitle': 'Ghi chú riêng tư & bí mật',
  'documentsTitle': 'Tài liệu',
  'documentsSubtitle': 'File cá nhân & đính kèm',
  'browseTitle': 'Duyệt',
  'browseSubtitle': 'Tất cả mục trong kho',
  'filterAll': 'Tất cả',
  'filterPasswords': 'Mật khẩu',
  'filterNotes': 'Ghi chú',
  'filterDocuments': 'Tài liệu',
  'filterFavorites': 'Yêu thích',
  'browseEmpty': 'Chưa có mục nào. Thêm từ Trang chủ!',
  'searchHint': 'Tìm trong kho...',
  'addItem': 'Thêm mục',
  'editItem': 'Sửa mục',
  'fieldTitle': 'Tiêu đề',
  'fieldUsername': 'Tên đăng nhập',
  'fieldPassword': 'Mật khẩu',
  'fieldUrl': 'URL trang web',
  'fieldContent': 'Nội dung',
  'fieldFile': 'File',
  'fieldNotes': 'Ghi chú (tùy chọn)',
  'fieldNotesHint': 'Ghi chú thêm...',
  'pickFile': 'Chọn file',
  'changeFile': 'Đổi file',
  'copyPassword': 'Sao chép mật khẩu',
  'copyUsername': 'Sao chép tên đăng nhập',
  'passwordCopied': 'Đã sao chép mật khẩu!',
  'usernameCopied': 'Đã sao chép tên đăng nhập!',
  'showPassword': 'Hiện',
  'hidePassword': 'Ẩn',
  'favorite': 'Yêu thích',
  'unfavorite': 'Bỏ yêu thích',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'deleteConfirm': 'Xóa mục này vĩnh viễn?',
  'itemSaved': 'Đã lưu!',
  'itemDeleted': 'Đã xóa',
  'listEmpty': 'Chưa có gì ở đây',
  'listEmptyAction': 'Thêm mục đầu tiên',
  'limitReached': 'Đã đạt giới hạn miễn phí ({limit} mục) — mở khóa không giới hạn tại Cửa hàng',
  'setupPinTitle': 'Tạo mã PIN',
  'setupPinDesc': 'Đặt mã PIN 4 số để bảo vệ kho',
  'confirmPinTitle': 'Xác nhận PIN',
  'confirmPinDesc': 'Nhập lại mã PIN để xác nhận',
  'pinMismatch': 'PIN không khớp. Thử lại.',
  'pinTooShort': 'PIN phải có ít nhất 4 số',
  'lockTitle': 'Daily Vault',
  'lockSubtitle': 'Nhập PIN để mở khóa',
  'lockWrongPin': 'PIN sai. Thử lại.',
  'unlockWithBiometric': 'Mở khóa bằng vân tay',
  'forgotPin': 'Quên mã PIN?',
  'forgotPinTitle': 'Đặt lại kho',
  'forgotPinDesc': 'Daily Vault lưu mọi thứ trên thiết bị. Không thể khôi phục PIN đã quên mà vẫn giữ dữ liệu.',
  'forgotPinOptionBio': 'Nếu đã bật vân tay, dùng vân tay mở app → Cài đặt → Đổi PIN.',
  'forgotPinOptionReset': 'Nếu không mở khóa được, bạn phải đặt lại kho. Mọi mật khẩu, ghi chú và tài liệu trên thiết bị sẽ bị xóa vĩnh viễn.',
  'forgotPinConfirm': 'Đặt lại & tạo PIN mới',
  'forgotPinCancel': 'Hủy',
  'forgotPinDone': 'Đã đặt lại kho. Hãy tạo PIN mới.',
  'biometricReason': 'Xác thực để mở Daily Vault',
  'changePin': 'Đổi PIN',
  'changePinDesc': 'Cập nhật mã PIN kho',
  'oldPin': 'PIN hiện tại',
  'newPin': 'PIN mới',
  'confirmNewPin': 'Xác nhận PIN mới',
  'pinChanged': 'Đã đổi PIN thành công',
  'pinChangeFailed': 'Không thể đổi PIN',
  'pinSameAsOld': 'PIN mới phải khác PIN hiện tại',
  'changePinStepCurrent': 'Nhập mã PIN 4 số hiện tại',
  'changePinStepNew': 'Chọn mã PIN 4 số mới',
  'changePinStepConfirm': 'Nhập lại PIN mới để xác nhận',
  'biometricLock': 'Mở khóa vân tay',
  'biometricLockDesc': 'Dùng vân tay hoặc khuôn mặt để mở khóa',
  'biometricNotAvailable': 'Sinh trắc học không khả dụng trên thiết bị này',
  'securitySection': 'Bảo mật',
  'adPlaceholder': 'Quảng cáo — Gỡ quảng cáo tại Cửa hàng',
  'settingsTitle': 'Cài đặt',
  'settingsSubtitle': 'Bảo mật & tùy chọn',
  'activeCustomization': 'Giao diện đang dùng',
  'activeTheme': 'Theme',
  'activeBackground': 'Hình nền',
  'activeSkin': 'Kiểu thẻ',
  'appearance': 'Giao diện',
  'darkMode': 'Chế độ tối',
  'premiumFeatures': 'Cao cấp',
  'exportData': 'Xuất kho',
  'exportDataDesc': 'Chia sẻ toàn bộ dữ liệu kho dạng text',
  'exportEmpty': 'Không có gì để xuất',
  'exportDone': 'Đã chia sẻ xuất!',
  'exportDate': 'Ngày xuất',
  'exportLocked': 'Mở khóa xuất dữ liệu tại Cửa hàng',
  'other': 'Khác',
  'language': 'Ngôn ngữ',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'openShop': 'Mở Cửa hàng',
  'openShopDesc': 'Mua sao, theme & tính năng',
  'privacyPolicy': 'Chính sách bảo mật',
  'copyright': '© Daily Vault. Dữ liệu kho lưu trên thiết bị của bạn.',
  'themeDefault': 'Mặc định',
  'bgDefault': 'Mặc định',
  'skinDefault': 'Mặc định',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Sao, theme & tính năng cao cấp',
  'shopBalance': 'Sao của bạn',
  'shopBuyStars': 'Mua sao',
  'shopBuyStarsDesc': 'Mua thêm sao qua Google Play',
  'shopEarnStars': 'Kiếm sao',
  'shopDailyReward': 'Thưởng hàng ngày',
  'shopDailyRewardDesc': 'Nhận {amount} sao mỗi ngày',
  'shopClaim': 'Nhận',
  'shopClaimed': 'Đã nhận hôm nay',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Cao cấp',
  'shopMenuThemes': 'Theme',
  'shopMenuCards': 'Hình nền',
  'shopMenuSkins': 'Kiểu thẻ',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có mục trong danh mục này',
  'shopOwned': 'Đã sở hữu',
  'shopActive': 'Đang dùng',
  'shopApply': 'Áp dụng',
  'shopResetDefault': 'Về mặc định',
  'shopBuy': 'Mua',
  'shopPrice': '{price} sao',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Trải nghiệm không quảng cáo vĩnh viễn',
  'shopThemeOcean': 'Xanh đại dương',
  'shopThemeOceanDesc': 'Tông xanh dịu mát',
  'shopThemeMidnight': 'Bầu trời đêm',
  'shopThemeMidnightDesc': 'Theme xanh trời sâu',
  'shopThemeEmerald': 'Ngọc lục bảo',
  'shopThemeEmeraldDesc': 'Theme xanh bảo mật tươi mát',
  'shopThemeRoyal': 'Tím hoàng gia',
  'shopThemeRoyalDesc': 'Giao diện tím sang trọng',
  'shopBgVault': 'Khiên Vault',
  'shopBgVaultDesc': 'Gradient navy kho bảo mật',
  'shopBgOcean': 'Sóng biển',
  'shopBgOceanDesc': 'Nền gradient đại dương',
  'shopBgAurora': 'Cực quang',
  'shopBgAuroraDesc': 'Gradient cực quang',
  'shopBgGalaxy': 'Galaxy',
  'shopBgGalaxyDesc': 'Gradient không gian sâu',
  'shopSkinNeon': 'Viền Neon',
  'shopSkinNeonDesc': 'Viền thẻ phát sáng teal',
  'shopSkinClassic': 'Vàng cổ điển',
  'shopSkinClassicDesc': 'Thẻ viền vàng ấm',
  'shopSkinGlass': 'Kính mờ',
  'shopSkinGlassDesc': 'Hiệu ứng kính mờ trên thẻ',
  'shopFeatUnlimitedItems': 'Không giới hạn',
  'shopFeatUnlimitedItemsDesc': 'Không giới hạn mật khẩu, ghi chú & tài liệu',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất toàn bộ kho',
  'shopFeatCustomFolders': 'Thư mục tùy chỉnh',
  'shopFeatCustomFoldersDesc': 'Sắp xếp mục trong thư mục riêng',
  'shopFeatSecureSharing': 'Chia sẻ bảo mật',
  'shopFeatSecureSharingDesc': 'Chia sẻ mục với bảo vệ thêm',
  'shopFeatNoWatermark': 'Không watermark',
  'shopFeatNoWatermarkDesc': 'Xuất sạch không logo',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại. Thử lại.',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'coinsAdded': 'Đã thêm sao vào số dư!',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'dailyRewardClaimed': 'Đã nhận thưởng hàng ngày!',
  'addPasswordRewardEarned': 'Nhận sao khi lưu mật khẩu!',
  'addNoteRewardEarned': 'Nhận sao khi lưu ghi chú!',
  'addDocumentRewardEarned': 'Nhận sao khi lưu tài liệu!',
  'shareRewardEarned': 'Nhận sao khi chia sẻ!',
  'billingDisabled': 'Google Play billing tạm thời không khả dụng',
  'configNetworkError': 'Không kết nối được server — dùng cài đặt đã lưu',
  'configTimeout': 'Server timeout — dùng cài đặt đã lưu',
  'coinPackTitle': 'Mua sao',
  'coinPackSubtitle': 'Chọn gói sao',
  'restorePurchases': 'Khôi phục mua hàng',
  'privacyTitle': 'Chính sách bảo mật',
  'privacyIntro': 'Daily Vault mặc định lưu mật khẩu, ghi chú, tài liệu, sao và vật phẩm cửa hàng ngay trên máy. Đăng nhập không bắt buộc. Chúng tôi không bán thông tin cá nhân.',
  'privacyData': 'Nội dung kho không rời thiết bị trừ khi bạn xuất hoặc chia sẻ. Nếu tạo tài khoản, chúng tôi lưu email, biệt danh và lịch sử mua pack trên server để gắn giao dịch với bạn. Chúng tôi không tải nội dung kho hay số sao lên.\n\nInternet còn dùng để lấy cấu hình IAP và xử lý mua hàng Google Play. Giao dịch do Google Play Billing xử lý. Chúng tôi không lưu thông tin thẻ.',
  'privacyContact': 'Liên hệ: support@dailyvault.app',
  'logNotes': 'Ghi chú',
  'yourWallet': 'Ví của bạn',
  'coinsLabel': 'Sao',
  'buyCoins': 'Mua sao',
  'buyCoinsDesc': 'Mua gói sao qua Google Play',
  'yourCoins': 'Bạn có {count} sao',
  'shopClaimedDaily': 'Đã nhận hôm nay',
  'shopClaimDaily': 'Nhận',
  'earnStepSavePassword': 'Lưu mật khẩu',
  'earnStepSavePasswordDesc': '+3 sao/mật khẩu (tối đa 10/ngày)',
  'earnStepSaveNote': 'Lưu ghi chú',
  'earnStepSaveNoteDesc': '+2 sao/ghi chú (tối đa 15/ngày)',
  'earnStepSaveDocument': 'Lưu tài liệu',
  'earnStepSaveDocumentDesc': '+5 sao/tài liệu (tối đa 3/ngày)',
  'earnStepShare': 'Chia sẻ kho',
  'earnStepShareDesc': '+5 sao khi chia sẻ xuất dữ liệu',
  'buyWithGooglePlay': 'Mua qua Google Play',
  'shopBrowse': 'Duyệt cửa hàng',
  'apply': 'Áp dụng',
  'applied': 'Đã áp dụng!',
  'resetDefault': 'Về mặc định',
  'resetToDefault': 'Đã về mặc định',
  'owned': 'Đã sở hữu',
  'openingBilling': 'Đang mở Google Play...',
  'removeAdsIap': 'Gỡ quảng cáo qua Google Play',
  'processingPurchase': 'Đang xử lý mua hàng...',
  'billingUnavailable': 'Billing không khả dụng trên thiết bị này',
  'productsNotFound': 'Không tìm thấy sản phẩm trên store',
  'earnCoinsHint': 'Kiếm sao bằng cách lưu mục hoặc nhận thưởng hàng ngày',
  'coinPack': 'Gói sao {num}',
  'coinAmount': '{count} sao',
  'coinRewardSub': 'Số dư: {balance} sao',
  'accountSection': 'Tài khoản',
  'accountGuestTitle': 'Chưa đăng nhập',
  'accountGuestDesc': 'Không bắt buộc — đăng nhập để lưu lịch sử mua pack.',
  'accountSignedIn': 'Đã đăng nhập',
  'accountShopHint': 'Đăng nhập để lưu lịch sử mua pack. Vẫn mua được khi chưa đăng nhập.',
  'authLoginTitle': 'Đăng nhập',
  'authRegisterTitle': 'Tạo tài khoản',
  'authLoginHeadline': 'Chào mừng trở lại',
  'authRegisterHeadline': 'Tạo tài khoản của bạn',
  'authOptionalHint': 'Đăng nhập không bắt buộc. Kho vẫn lưu trên máy — chỉ cần tài khoản để lưu lịch sử mua pack.',
  'authEmail': 'Email',
  'authPassword': 'Mật khẩu',
  'authNickname': 'Biệt danh',
  'authNicknameHint': 'Hiện trên tài khoản',
  'authLoginAction': 'Đăng nhập',
  'authRegisterAction': 'Đăng ký',
  'authNeedAccount': 'Chưa có tài khoản? Đăng ký',
  'authHaveAccount': 'Đã có tài khoản? Đăng nhập',
  'authLogout': 'Đăng xuất',
  'authLogoutConfirm': 'Đăng xuất trên máy này? Kho, PIN và sao vẫn giữ trên điện thoại.',
  'authLogoutSuccess': 'Đã đăng xuất',
  'authLoginSuccess': 'Đã đăng nhập',
  'authRegisterSuccess': 'Đã tạo tài khoản',
  'authEmailRequired': 'Nhập email',
  'authEmailInvalid': 'Email không hợp lệ',
  'authPasswordShort': 'Mật khẩu phải từ 6 ký tự',
  'authEmailTaken': 'Email này đã được đăng ký',
  'authInvalidCredentials': 'Email hoặc mật khẩu không đúng',
  'authAccountLocked': 'Tài khoản này đã bị khóa',
  'authValidationError': 'Kiểm tra lại email và mật khẩu',
  'authNetworkError': 'Lỗi mạng. Thử lại.',
  'authUnknownError': 'Có lỗi xảy ra. Thử lại.',
};
